# Generated by Django 4.1.5 on 2023-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('palaute', models.TextField(max_length=1000)),
                ('sposti', models.EmailField(max_length=150)),
            ],
        ),
    ]
